channels:
  - conda-forge
  - bioconda
#  - r
dependencies:
  - snakemake-minimal=6.4.1 
  - pandas=1.2.5
  - pathlib=1.0.1
#  - diamond=2.0.9
#  - git=2.30.2
#  - ant=1.10.0
#  - r-base=4.1.0
#  - graphviz=2.47.3
