import pandas as pd
from pathlib import Path

configfile: "config/config.yaml"

species_table = pd.read_table("resources/species.tsv").set_index("species")
SPECIES = species_table.index.tolist()

include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/extract_header_and_length.smk"
include: "rules/diamond.smk"
include: "rules/get_ahrd.smk"
include: "rules/create_ahrd_input.smk"
include: "rules/run_ahrd.smk"
include: "rules/busco.smk"
include: "rules/get_ProtSpaM.smk"
include: "rules/run_ProtSpaM.smk"

rule busco_all:
    input:
        expand("results/{species}_busco", species=SPECIES)

rule ProtSpaM:
    input:
        rules.run_ProtSpaM.output

rule all:
    input:
        expand("results/{species}.ahrd_output.tsv", species=SPECIES)

