import pandas as pd
from pathlib import Path

configfile: "config/config.yaml"

species_table = pd.read_table("resources/species.tsv").set_index("species")
SPECIES = species_table.index.tolist()

include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/extract_header_and_length.smk"
include: "rules/blast.smk"
include: "rules/get_ahrd.smk"
include: "rules/create_ahrd_input.smk"
include: "rules/run_ahrd.smk"

rule all:
    input:
        expand("results/{species}.ahrd_output.tsv", species=SPECIES)

rule download_all:
    input:
        query = rules.download_ecoli.output,
        sprotDb = rules.download_swissprot.output,
        unirefDb = rules.download_uniref50.output,
        goa = rules.download_goa.output
