fa <- snakemake@params[["fa"]]
goa <- snakemake@params[["goa"]]
sprot <- snakemake@params[["sprot"]]
uniref90 <- snakemake@params[["uniref90"]]
diamondSprot <- snakemake@params[["diamondSprot"]]
diamondUniref90 <- snakemake@params[["diamondUniref90"]]
ahrdOutput <- snakemake@params[["ahrdOutput"]]
ahrd_loc <- gsub("dist/ahrd.jar", "", snakemake@params[["jar"]])
outFile <- snakemake@output[[1]]
threads <- 8
hrd_parms <- c(0.6042, 0.3751, 0.0208, 41, 10.373078, 30, 3) #/gpfs/project/cb/ahrd/experiments/uniprot_VS_uniref_IN_gzippedDBs/nrSprotExpGOAv4_uniref90_training10_HRD_output.tsv
go_parms <- c(0.9222, 0.0558, 0.0219, 0.052092, 0.086514, 195, 12.397316, 140, 2.547707) #/gpfs/project/cb/ahrd/experiments/uniprot_VS_uniref_IN_gzippedDBs/nrSprotExpGOAv4_uniref90_training2_GO_output.tsv 

# Write YML file with the retrieved weights
cat(paste("proteins_fasta: ", fa, sep=""), file=outFile, append=F, sep="\n")
cat(paste("n_threads: ", threads, sep=""), file=outFile, append=T, sep="\n")
cat(paste("blacklist: ", ahrd_loc, "test/resources/blacklist_descline.txt", sep=""), file=outFile, append=T, sep="\n")
cat(paste("token_blacklist: ", ahrd_loc, "test/resources/blacklist_token.txt", sep=""), file=outFile, append=T, sep="\n")
cat(paste("output: ", ahrdOutput, sep=""), file=outFile, append=T, sep="\n")
cat("", file=outFile, append=T, sep="\n")
cat("blast_dbs:", file=outFile, append=T, sep="\n")
cat("  swissprot:", file=outFile, append=T, sep="\n")
cat(paste("    file: ", diamondSprot, sep=""), file=outFile, append=T, sep="\n")
cat(paste("    database: ", sprot, sep=""), file=outFile, append=T, sep="\n")
cat(paste("    filter: ", ahrd_loc , "test/resources/filter_descline_sprot.txt", sep=""), file=outFile, append=T, sep="\n")
cat("  uniref:", file=outFile, append=T, sep="\n")
cat(paste("    file: ", diamondUniref90, sep=""), file=outFile, append=T, sep="\n")
cat("    short_accession_regex: \"^[^_]+_(?<shortAccession>[^_]+)$\"", file=outFile, append=T, sep="\n")
cat(paste("    database: ", uniref90, sep=""), file=outFile, append=T, sep="\n")
cat(paste("    filter: ", ahrd_loc, "test/resources/filter_descline_uniref.txt", sep=""), file=outFile, append=T, sep="\n")
cat("", file=outFile, append=T, sep="\n")
cat("description_settings:", file=outFile, append=T, sep="\n")
cat(paste("  token_score_bit_score_weight:", hrd_parms[1]), file=outFile, append=T, sep="\n")
cat(paste("  token_score_database_score_weight:", hrd_parms[2]), file=outFile, append=T, sep="\n")
cat(paste("  token_score_overlap_score_weight:", hrd_parms[3]), file=outFile, append=T, sep="\n")
cat("  blast_dbs:", file=outFile, append=T, sep="\n")
cat("    swissprot:", file=outFile, append=T, sep="\n")
cat(paste("      weight:", hrd_parms[4]), file=outFile, append=T, sep="\n")
cat(paste("      annotation_score_bit_score_weight:", hrd_parms[5]), file=outFile, append=T, sep="\n")
cat("    uniref:", file=outFile, append=T, sep="\n")
cat(paste("      weight:", hrd_parms[6]), file=outFile, append=T, sep="\n")
cat(paste("      annotation_score_bit_score_weight:", hrd_parms[7]), file=outFile, append=T, sep="\n")
cat("", file=outFile, append=T, sep="\n")
cat("go_settings:", file=outFile, append=T, sep="\n")
cat(paste("  token_score_bit_score_weight:", go_parms[1]), file=outFile, append=T, sep="\n")
cat(paste("  token_score_database_score_weight:", go_parms[2]), file=outFile, append=T, sep="\n")
cat(paste("  token_score_overlap_score_weight:", go_parms[3]), file=outFile, append=T, sep="\n")
cat(paste("  informative_token_threshold:", go_parms[4]), file=outFile, append=T, sep="\n")
cat(paste("  go_term_score_evidence_code_weight:", go_parms[5]), file=outFile, append=T, sep="\n")
cat("  blast_dbs:", file=outFile, append=T, sep="\n")
cat("    swissprot:", file=outFile, append=T, sep="\n")
cat(paste("      weight:", go_parms[6]), file=outFile, append=T, sep="\n")
cat(paste("      annotation_score_bit_score_weight:", go_parms[7]), file=outFile, append=T, sep="\n")
cat(paste("      gene_ontology_reference: ", goa, sep=""), file=outFile, append=T, sep="\n")
cat("    uniref:", file=outFile, append=T, sep="\n")
cat(paste("      weight:", go_parms[8]), file=outFile, append=T, sep="\n")
cat(paste("      annotation_score_bit_score_weight:", go_parms[9]), file=outFile, append=T, sep="\n")
cat("  reference_go_annotation_evidence_code_weights:", file=outFile, append=T, sep="\n")
cat("    ISS: 0.4", file=outFile, append=T, sep="\n")
cat("    ISO: 0.4", file=outFile, append=T, sep="\n")
cat("    ISA: 0.4", file=outFile, append=T, sep="\n")
cat("    ISM: 0.4", file=outFile, append=T, sep="\n")
cat("    IGC: 0.4", file=outFile, append=T, sep="\n")
cat("    IBA: 0.4", file=outFile, append=T, sep="\n")
cat("    IBD: 0.4", file=outFile, append=T, sep="\n")
cat("    IKR: 0.4", file=outFile, append=T, sep="\n")
cat("    IRD: 0.4", file=outFile, append=T, sep="\n")
cat("    RCA: 0.4", file=outFile, append=T, sep="\n")
cat("    TAS: 0.4", file=outFile, append=T, sep="\n")
cat("    NAS: 0.2", file=outFile, append=T, sep="\n")
cat("    IC: 0.4", file=outFile, append=T, sep="\n")
cat("    ND: 0.1", file=outFile, append=T, sep="\n")
cat("    IEA: 0.2", file=outFile, append=T, sep="\n")
cat("    NR: 0.0", file=outFile, append=T, sep="\n")
